/* ============================================================
 *  content.js - SINGLE SOURCE OF TRUTH FOR THE WHOLE SITE
 *  ------------------------------------------------------------
 *  Every word, link and list on the page is rendered from this
 *  file (articles come from js/blog-data.js, generated by the
 *  content pipeline). Edit values here, save, refresh.
 * ============================================================ */

window.CONTENT = {

  /* ---------- Identity ---------- */
  profile: {
    firstName: 'Mohit',
    lastName: 'Malhotra',
    role: 'Staff Software Engineer',
    focus: 'Distributed Systems · System Design · IoT · Platforms',
    company: 'Celigo',
    companyUrl: 'https://www.celigo.com',
    location: 'Hyderabad, India',
    availability: 'Open to hard problems',

    /* Identity chips shown in the landing hero */
    identities: ['Open Source Contributor', 'Technical Writer', 'Technology Consultant', 'Software R&D'],

    tagline:
      'From the world\'s smallest ventilator to a 60-million-device IoT platform to enterprise iPaaS: a decade of systems that ship, scale and stay up.',

    about: [
      'I\'m Mohit, a Staff Software Engineer with a decade-long arc that reads like a systems tour: founded a books marketplace at 21, built the software behind the world\'s smallest portable ventilator and India\'s first Ventilator Remote Management System at AgVa Healthcare, then led platform engineering at Barco, where a device registry I designed keeps 60+ million devices consistent across SAP, Salesforce and Flexera.',
      'Today I build next-gen iPaaS at Celigo: high-scale IO systems for files and databases that automate business processes for millions of businesses across North America and Europe. The thread through all of it is correctness meeting performance, whether that\'s C++ on an operating-room device or Node.js microservices on Kubernetes.',
      'Beyond the day job I write deep-dive essays read by thousands of engineers across 11 Medium publications, and make open source contributions to the tools I depend on: Node.js, the Azure IoT SDK and MySQL\'s official Node.js connector.',
    ],

    email: 'dev.mohitmalhotra@gmail.com',
    resumeUrl: '', // optional link to a PDF résumé; leave '' to hide the button

    socials: {
      linkedin: 'https://www.linkedin.com/in/dev-mohit-malhotra',
      github: 'https://github.com/MOHIT51196',
      medium: 'https://medium.com/@mohit-malhotra',
      twitter: 'https://twitter.com/imohitmalhotra',
    },
  },

  /* ---------- Experience (editorial rows, newest first) ---------- */
  experience: [
    {
      company: 'Celigo',
      role: 'Staff Software Engineer',
      period: 'May 2025 to Present',
      location: 'Hyderabad, IN',
      summary:
        'Building the next-gen iPaaS that automates business processes for enterprises: high-scale IO systems for files and databases powering integrations for millions of businesses across North America and Europe.',
      tags: ['Node.js', 'MongoDB', 'AWS', 'Snowflake', 'WebSocket', 'New Relic'],
    },
    {
      company: 'Open Source Projects',
      role: 'Open Source Contributor',
      period: 'Jun 2023 to Present',
      location: 'Part-time · Remote',
      summary:
        'Open source contributions to high-impact projects powering millions of products and organisations: Node.js, the Azure IoT SDK and MySQL Connector/Node.js.',
      tags: ['Node.js', 'C++', 'Docker', 'CMake'],
    },
    {
      company: 'Medium',
      role: 'Technical Writer',
      period: '2020 to Present',
      location: 'medium.com/@mohit-malhotra',
      summary:
        '35+ deep-dive essays on distributed systems, Node.js internals and backend performance, published across 11 publications including Level Up Coding, The Startup and JavaScript in Plain English.',
      tags: ['Distributed Systems', 'Node.js', 'System Design', 'Technical Writing'],
    },
    {
      company: 'Barco',
      role: 'Lead Platform Engineer',
      period: 'Nov 2022 to May 2025',
      location: 'Noida, IN · Hybrid',
      summary:
        'Designed the highly scalable, strongly consistent device registry aggregating data from SAP, Salesforce and Flexera for 60+ million devices in production. Built next-gen edge computing for NexxisCare operating rooms, and the core C++ IoT SDKs that keep those devices connected with low latency.',
      tags: ['C++17', 'TypeScript', 'NestJS', 'Azure IoT', 'Kubernetes', 'Edge Computing'],
    },
    {
      company: 'AgVa Healthcare',
      role: 'Technical Head · Software R&D',
      period: 'Sep 2018 to Nov 2022',
      location: 'Noida, IN',
      summary:
        'Four years from Lead Software Researcher to Technical Head. Designed the software for the world\'s smallest app-controlled turbine ventilator, researched India\'s first Ventilator Remote Management System, rendered live respiratory dynamics in under 100ms on mobile, and headed R&D across 5–6 innovative medical products.',
      tags: ['IoT', 'BLE', 'React', 'Express.js', 'Flutter', 'Qt', 'Java'],
    },
    {
      company: 'Independent',
      role: 'Freelance Software Engineer',
      period: '2018 to Present',
      location: 'Worldwide · Remote',
      summary:
        'Working globally as a freelance engineer solving problems at scale: product engineering, architecture reviews and app development for founders and teams across time zones, including a senior app developer engagement at Kkekk and Reclancers, a talent-acquisition platform in active development.',
      tags: ['Full-stack', 'System Design', 'Consulting', 'Architecture'],
    },
    {
      company: 'KitabiKidda.com',
      role: 'Founder',
      period: 'Nov 2015 to Jan 2017',
      location: 'New Delhi, IN',
      summary:
        'Founded and led a Delhi-based e-commerce startup for second-hand books, a collaborative platform for students and enthusiasts, because books deserve shelves, not dump yards.',
      tags: ['Entrepreneurship', 'WordPress', 'Product', 'Team Building'],
    },
  ],

  /* ---------- Beyond the day job (highlight band) ---------- */
  beyond: [
    {
      big: '35+',
      title: 'Technical Writer',
      sub: 'Deep-dive essays across 11 Medium publications: Level Up Coding, The Startup, JS in Plain English and more.',
      linkLabel: 'Read on Medium',
      link: 'https://medium.com/@mohit-malhotra',
    },
    {
      big: 'OSS',
      title: 'Open Source Contributor',
      sub: 'Open source contributions to Node.js, the Azure IoT SDK and MySQL Connector/Node.js.',
      linkLabel: 'GitHub profile',
      link: 'https://github.com/MOHIT51196',
    },
    {
      big: '2015→',
      title: 'Founder & Freelancer',
      sub: 'Founded KitabiKidda.com at 21; freelance product engineering and architecture ever since.',
      linkLabel: 'Work with me',
      link: 'contact.html',
    },
  ],

  /* ---------- Products I helped build (Work page, first section) ---------- */
  products: [
    {
      name: 'Celigo Platform',
      domain: 'celigo.com',
      kind: 'Enterprise iPaaS',
      url: 'https://www.celigo.com/',
      about: 'The #1-rated integration platform. Thousands of enterprises automate their business processes on it, from order-to-cash to procure-to-pay.',
      built: 'High-scale IO systems for files and databases at the heart of the platform, moving data reliably for millions of businesses across North America and Europe.',
      tags: ['Node.js', 'MongoDB', 'AWS', 'Snowflake'],
    },
    {
      name: 'Barco · NexxisCare & IoT Platform',
      domain: 'barco.com',
      kind: 'MedTech · Enterprise IoT',
      url: 'https://www.barco.com/',
      about: 'Global leader in visualization and healthcare technology: operating-room imaging, control rooms and a fleet of tens of millions of connected devices.',
      built: 'The strongly consistent device registry aggregating SAP, Salesforce and Flexera data for 60+ million devices, next-gen edge computing for NexxisCare operating rooms, and the low-latency C++ IoT SDKs keeping those devices connected.',
      tags: ['C++17', 'Azure IoT', 'Kubernetes', 'NestJS', 'Edge Computing'],
    },
    {
      name: 'AgVa Ventilators & VRMS',
      domain: 'agvahealthtech.com',
      kind: 'Medical Devices',
      url: 'https://www.agvahealthtech.com/',
      about: 'The world\'s smallest ICU-grade ventilators: app-controlled, turbine-driven, now sold as the AVAC line by D&D Healthcare.',
      built: 'The complete software stack: mobile-app ventilation control over BLE, India\'s first Ventilator Remote Management System, and live respiratory dynamics rendered in under 100 milliseconds.',
      tags: ['IoT', 'BLE', 'React', 'Qt', 'Flutter'],
    },
    {
      name: 'Reclancers',
      domain: 'reclancers.com',
      kind: 'Talent Platform · In development',
      url: 'https://reclancers.com/',
      about: 'A global talent-acquisition platform in active development, rethinking how companies find and hire talent across borders.',
      built: 'Building it from the ground up: product architecture and the full engineering stack, applying a decade of distributed-systems practice to hiring at global scale.',
      tags: ['System Design', 'Full-stack', 'Node.js'],
    },
  ],

  /* ---------- Open source contributions ---------- */
  openSource: [
    {
      name: 'Node.js',
      description: 'Contributions to the official Node.js runtime, the platform behind most of my production work and half of my writing.',
      lang: 'C++ · JavaScript',
      url: 'https://github.com/nodejs/node',
    },
    {
      name: 'Azure IoT C SDK',
      description: 'Contributions to Microsoft\'s official device SDK, the same C toolchain I used to keep 60+ million devices connected at Barco.',
      lang: 'C',
      url: 'https://github.com/Azure/azure-iot-sdk-c',
    },
    {
      name: 'MySQL Connector/Node.js',
      description: 'Contributions to MySQL\'s official Node.js connector, where database performance meets driver internals.',
      lang: 'JavaScript · MySQL',
      url: 'https://github.com/mysql/mysql-connector-nodejs',
    },
  ],

  /* ---------- Stack ticker (news-ticker under the hero) ----------
   * Two mutually exclusive rows: core stack on top, practices and
   * tooling below (scrolls the opposite way, slower). */
  stackTicker: [
    'Node.js', 'C++', 'TypeScript', 'Java', 'Go', 'Python', 'Kubernetes',
    'Docker', 'AWS', 'Azure IoT', 'MongoDB', 'MySQL', 'Snowflake',
  ],
  stackTickerAlt: [
    'Distributed Systems', 'System Design', 'Microservices', 'Event-Driven Design',
    'Edge Computing', 'WebSocket', 'NestJS', 'Spring Boot', 'GraphQL',
    'Grafana', 'Splunk', 'New Relic', 'CI/CD',
  ],

  /* ---------- Stack groups (used by the terminal `stack` command) ---------- */
  skills: [
    {
      group: 'Languages',
      items: ['Node.js / JavaScript', 'TypeScript', 'Modern C++ (11/14/17)', 'Java', 'Go', 'Python', 'Kotlin'],
    },
    {
      group: 'Backend & Architecture',
      items: ['Microservices', 'Distributed Systems', 'Event-Driven Design', 'NestJS · Express', 'Spring Boot', 'REST · WebSockets · GraphQL', 'System Design'],
    },
    {
      group: 'Cloud, IoT & Platform',
      items: ['Kubernetes', 'Docker · podman', 'AWS', 'Azure IoT · Edge Computing', 'GitHub Actions CI/CD', 'BLE & embedded integration', 'Linux'],
    },
    {
      group: 'Data & Observability',
      items: ['MongoDB', 'MySQL', 'Snowflake', 'Firebase', 'Grafana · Graphite', 'Splunk', 'New Relic'],
    },
  ],

  /* ---------- Certifications (newest first) ---------- */
  certifications: [
    { name: 'Graphite and Grafana: Visualizing Application Performance', issuer: 'LinkedIn Learning', year: '2025' },
    { name: 'Build a Microservice with Go', issuer: 'LinkedIn Learning', year: '2024' },
    { name: 'Learning Amazon Web Services (AWS) for Developers', issuer: 'LinkedIn Learning', year: '2024' },
    { name: 'Learning GitHub Actions', issuer: 'LinkedIn Learning', year: '2023' },
    { name: 'Achieving Low-Latency Data with Edge Computing', issuer: 'LinkedIn Learning', year: '2023' },
    { name: 'Learning Kubernetes', issuer: 'LinkedIn Learning', year: '2023' },
    { name: 'Azure Cloud Design Patterns', issuer: 'LinkedIn Learning', year: '2023' },
    { name: 'Azure Data Factory', issuer: 'LinkedIn Learning', year: '2023' },
    { name: 'Advanced Microservices: Tactical Forking', issuer: 'LinkedIn Learning', year: '2023' },
    { name: 'Agile PM 301: Mastering Agile Project Management', issuer: 'Udemy', year: '2022' },
    { name: 'Fundamentals of Backend Engineering', issuer: 'Udemy', year: '' },
    { name: 'Software Architecture and Design Essentials', issuer: 'Udemy', year: '' },
    { name: 'Complete Modern C++ (C++11/14/17)', issuer: 'Udemy', year: '' },
    { name: 'Flutter & Dart: The Complete Flutter App Development Course', issuer: 'Udemy', year: '' },
  ],

  /* ---------- Testimonials: all 7 LinkedIn recommendations ---------- */
  recommendations: [
    {
      quote:
        'It\'s been a pleasure working with Mohit in the IoT team. Finding someone skilled in both C++ and Node.js is rare, and Mohit truly stands out with his expertise in both areas. He contributed across very different domains, from developing IoT Agents on devices to building microservices running on Kubernetes. His versatility and ability to handle such varied responsibilities with ease are highly impressive. Mohit did an excellent job during his time with us, consistently delivering quality results.',
      author: 'Sanjeev Kumar',
      title: 'Product Owner · IoT',
      company: 'Barco',
    },
    {
      quote:
        'One thing that really stood out to me was Mohit\'s talent for design and coding, especially in C++. He wrote code that was not just efficient, but also clean and easy for the rest of us to understand. Whenever we hit a tricky problem, he would jump in with thoughtful solutions, whether it was optimizing device performance or making sure our systems worked smoothly together. I\'d highly recommend Mohit to any team looking for someone who\'s not only a C++ expert but also a great collaborator and problem solver.',
      author: 'Amitabh Modak',
      title: 'Senior Solution Architect · AI & Azure',
      company: 'Barco',
    },
    {
      quote:
        'Mohit consistently proved to be a dependable and proactive team member. He contributed across the board, whether it was bug fixes, build management, support, feature development, or driving new initiatives. He brought fresh perspectives to team discussions, was never afraid to experiment with new ideas, and always approached challenges with a problem-solving mindset. His sense of ownership and willingness to go the extra mile truly stood out.',
      author: 'Vikas Mundra',
      title: 'Associate Technical Specialist',
      company: 'Barco',
    },
    {
      quote:
        'I worked with Mohit Malhotra at Barco Electronics and always found him to be a dependable and proactive team member. He contributed across the board: bug fixes, builds, support, feature development, and even new initiatives. Mohit was vocal in discussions, brought fresh ideas, and was always up for trying new things. His problem-solving mindset and ownership really stood out. I\'d be happy to work with him again.',
      author: 'Vikrant Jain',
      title: 'Architect · Distributed Systems & Cloud Platforms',
      company: 'Barco · Mentor',
    },
    {
      quote:
        'Mohit is an excellent team player who always goes the extra mile to ensure that his work is of the highest quality. His attention to detail and commitment to delivering projects on time have been exceptional. He is a quick learner and adapts well to new environments, making him an asset to any team. His ability to present complex ideas in a clear and concise manner has been invaluable to our team.',
      author: 'Ayush Gupta',
      title: 'Developer · World\'s Smallest Portable Ventilator',
      company: 'AgVa Healthcare',
    },
    {
      quote:
        'In my complete experience, I\'ve met a lot of people but Mohit was a complete problem solver. He\'s not only a great tech guy but also a great person. Always keen to learn new things makes him stand out from others.',
      author: 'Vaibhav Gupta',
      title: 'Senior Consultant · Technical Lead · Embedded',
      company: 'Barco',
    },
    {
      quote:
        'I rarely come across real talents who stand out like Mohit. I had the pleasure of working with Mohit for three years at AgVa Healthcare, collaborating on several projects. Mohit\'s ability to handle multiple projects was unlike any I\'ve seen before and made a great increase in the software development part of our company. He handles his team fluidically and has great skills in application development. As a team member or a leader, Mohit earns my highest recommendation.',
      author: 'Anshuman Dikshit',
      title: 'Product Development · Medical Devices',
      company: 'AgVa Healthcare',
    },
  ],

  /* ---------- System anatomy (exploded 3D view) ----------
   * Each layer lists the skill set Mohit offers at that stage. */
  anatomy: [
    {
      name: 'Clients',
      desc: 'Browsers, devices, partner systems: untrusted, bursty, everywhere.',
      skills: ['WebSockets', 'REST APIs', 'Flutter', 'React'],
    },
    {
      name: 'Edge & Gateway',
      desc: 'TLS termination, auth, rate limiting. The only door in.',
      skills: ['Edge Computing', 'Azure IoT Edge', 'API Gateways', 'Auth & rate limiting'],
    },
    {
      name: 'Service Mesh',
      desc: 'Discovery, retries, circuit breakers. Failure contained by default.',
      skills: ['Kubernetes', 'Docker · podman', 'Circuit breakers', 'Service discovery'],
    },
    {
      name: 'Services',
      desc: 'Small, single-purpose, independently deployable. The business lives here.',
      skills: ['Node.js · NestJS', 'C++ 11/14/17', 'Go · Java · Spring Boot', 'System design'],
    },
    {
      name: 'Async Backbone',
      desc: 'Queues and streams absorbing spikes, decoupling producers from consumers.',
      skills: ['Event-driven design', 'Message queues', 'WebSocket streams', 'Backpressure control'],
    },
    {
      name: 'Data & Observability',
      desc: 'Stores chosen per access pattern; traces, metrics and logs watching it all.',
      skills: ['MongoDB · MySQL', 'Snowflake', 'Grafana · Graphite', 'Splunk · New Relic'],
    },
  ],

  /* ---------- Contact ---------- */
  contact: {
    heading: 'Have a hard problem?',
    sub: 'I like the ones involving scale, consistency, or both. My inbox is open for roles, consulting or a good systems argument.',
    ctaLabel: 'Say hello',
  },
};
